language: php
php:
  - '7.2'
install:
  - mkdir -p ext/magento/adobe-stock-integration
  - mv !(ext) ext/magento/adobe-stock-integration/
  - composer config --global http-basic.repo.magento.com "$MAGENTO_USERNAME" "$MAGENTO_PASSWORD"
  - git clone https://github.com/magento/magento2
  - cd magento2
  - composer install
  - composer config minimum-stability dev
  - composer config repositories.ext path "../ext/*/*/*"
  - composer require magento/adobe-stock-integration
before_script:
  - echo "vendor/magento/module-adobe-stock-*" > dev/tests/static/testsuite/Magento/Test/Php/_files/whitelist/common.txt
  - sed -i 's/name="TESTCODESTYLE_IS_FULL_SCAN" value="0"/name="TESTCODESTYLE_IS_FULL_SCAN" value="1"/g' dev/tests/static/phpunit.xml.dist
env:
  matrix:
    - TEST_CATEGORY=static
    - TEST_CATEGORY=unit_ims
    - TEST_CATEGORY=unit_client
    - TEST_CATEGORY=unit_image
    - TEST_CATEGORY=unit_ui
    - TEST_CATEGORY=unit_image_ui
matrix:
  fast_finish: true
script:
  - if [ $TEST_CATEGORY == 'unit_ims' ]; then vendor/bin/phpunit --configuration dev/tests/unit/phpunit.xml.dist vendor/magento/module-adobe-ims/Test/Unit; fi
  - if [ $TEST_CATEGORY == 'unit_client' ]; then vendor/bin/phpunit --configuration dev/tests/unit/phpunit.xml.dist vendor/magento/module-adobe-stock-client/Test/Unit; fi
  - if [ $TEST_CATEGORY == 'unit_ui' ]; then vendor/bin/phpunit --configuration dev/tests/unit/phpunit.xml.dist vendor/magento/module-adobe-stock-admin-ui/Test/Unit; fi
  - if [ $TEST_CATEGORY == 'unit_image' ]; then vendor/bin/phpunit --configuration dev/tests/unit/phpunit.xml.dist vendor/magento/module-adobe-stock-image/Test/Unit; fi
  - if [ $TEST_CATEGORY == 'unit_image_ui' ]; then vendor/bin/phpunit --configuration dev/tests/unit/phpunit.xml.dist vendor/magento/module-adobe-stock-image-admin-ui/Test/Unit; fi
  - if [ $TEST_CATEGORY == 'static' ]; then vendor/bin/phpunit --configuration dev/tests/static/phpunit.xml.dist dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php; fi